-- MySQL Script generated by MySQL Workbench
-- Mon Sep  6 21:54:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipaje` (
  `idEquipaje_eq` VARCHAR(6) NOT NULL,
  `Peso_eq` INT NULL,
  `Sobredimensionado_eq` VARCHAR(2) NULL,
  `Valor_eq` FLOAT NULL,
  PRIMARY KEY (`idEquipaje_eq`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pasajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pasajero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pasajero` (
  `idPasajero` INT NOT NULL,
  `Cedula_pas` INT NOT NULL,
  `Nombre_pas` VARCHAR(45) NULL,
  `Sexo_pas` VARCHAR(45) NULL,
  `Direccion_pas` VARCHAR(45) NULL,
  `Telefono_pas` INT NULL,
  `VIP_pas` VARCHAR(45) NULL,
  `Edad_pas` VARCHAR(45) NULL,
  `Equipaje_idEquipaje` VARCHAR(6) NULL,
  PRIMARY KEY (`idPasajero`, `Cedula_pas`),
  INDEX `fk_Pasajero_Equipaje1_idx` (`Equipaje_idEquipaje` ASC) VISIBLE,
  CONSTRAINT `fk_Pasajero_Equipaje1`
    FOREIGN KEY (`Equipaje_idEquipaje`)
    REFERENCES `mydb`.`Equipaje` (`idEquipaje_eq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autobus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autobus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autobus` (
  `idAutobus` INT NOT NULL,
  `Capacidad_bus` INT NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo_bus` VARCHAR(45) NULL,
  `Compañia_bus` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutobus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terminal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terminal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terminal` (
  `idTerminal_term` INT NOT NULL,
  `Ciudad_term` VARCHAR(45) NULL,
  `Aforo_term` INT NULL,
  `Numero empleados_term` INT NULL,
  PRIMARY KEY (`idTerminal_term`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ruta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ruta` (
  `Terminal_idTerminal` INT NOT NULL,
  `Autobus_idAutobus` INT NOT NULL,
  `Sillas_disponibles_rut` INT NULL,
  `Fecha_de_salida_rut` DATE NULL,
  `Precio_rut` INT NULL,
  `idRuta_rut` INT NOT NULL,
  `Destino_Ruta` VARCHAR(45) NULL,
  PRIMARY KEY (`Terminal_idTerminal`, `Autobus_idAutobus`, `idRuta_rut`),
  INDEX `fk_Terminal_has_Autobus_Autobus1_idx` (`Autobus_idAutobus` ASC) VISIBLE,
  INDEX `fk_Terminal_has_Autobus_Terminal1_idx` (`Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Terminal_has_Autobus_Terminal1`
    FOREIGN KEY (`Terminal_idTerminal`)
    REFERENCES `mydb`.`Terminal` (`idTerminal_term`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terminal_has_Autobus_Autobus1`
    FOREIGN KEY (`Autobus_idAutobus`)
    REFERENCES `mydb`.`Autobus` (`idAutobus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Numero_Ticket` VARCHAR(6) NOT NULL,
  `Pasajero_idPasajero` INT NOT NULL,
  `Ruta_Terminal_idTerminal` INT NOT NULL,
  `Ruta_Autobus_idAutobus` INT NOT NULL,
  `Ruta_idRuta` INT NOT NULL,
  PRIMARY KEY (`Numero_Ticket`, `Pasajero_idPasajero`, `Ruta_Terminal_idTerminal`, `Ruta_Autobus_idAutobus`, `Ruta_idRuta`),
  INDEX `fk_Autobus_has_Pasajero_Pasajero1_idx` (`Pasajero_idPasajero` ASC) VISIBLE,
  INDEX `fk_Ticket_Ruta1_idx` (`Ruta_Terminal_idTerminal` ASC, `Ruta_Autobus_idAutobus` ASC, `Ruta_idRuta` ASC) VISIBLE,
  CONSTRAINT `fk_Autobus_has_Pasajero_Pasajero1`
    FOREIGN KEY (`Pasajero_idPasajero`)
    REFERENCES `mydb`.`Pasajero` (`idPasajero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Ruta1`
    FOREIGN KEY (`Ruta_Terminal_idTerminal` , `Ruta_Autobus_idAutobus` , `Ruta_idRuta`)
    REFERENCES `mydb`.`Ruta` (`Terminal_idTerminal` , `Autobus_idAutobus` , `idRuta_rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado_emp` INT NOT NULL,
  `Tipo_emp` VARCHAR(45) NULL,
  `Turno_emp` DATE NULL,
  `Terminal_idTerminal` INT NOT NULL,
  PRIMARY KEY (`idEmpleado_emp`, `Terminal_idTerminal`),
  INDEX `fk_Empleado_Terminal1_idx` (`Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Terminal1`
    FOREIGN KEY (`Terminal_idTerminal`)
    REFERENCES `mydb`.`Terminal` (`idTerminal_term`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
