# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191EXt1lvdPO0ER0WV9zntnvOUC7Smp0j
"""

# comparar a con b y saber cuales no tiene b
a = [3,5,7,10,15,16]
b = [4,10,5,8]

repetidos = []

for i in range(len(b)):
  for j in range(len(a)):
    #print(b[i], a[j])
    if b[i] == a[j]:
      repetidos.append(a[j])

#print(repetidos)  # ambos los tenemos

noTengoYo = []

for i in range(len(a)):
  if a[i] not in repetidos:
    noTengoYo.append(a[i])

print(noTengoYo)



