-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 00:55:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Terminal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terminal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Terminal` (
  `idTerminal` INT NOT NULL,
  `Aforo` INT NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerminal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pasajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pasajero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pasajero` (
  `idPasajero` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nacionalidad` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Residencia` VARCHAR(45) NOT NULL,
  `Ciudad de Destino` VARCHAR(45) NOT NULL,
  `Ciudad Procedencia` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Terminal_idTerminal` INT NOT NULL,
  `Cedula` INT NULL,
  PRIMARY KEY (`idPasajero`, `Terminal_idTerminal`),
  INDEX `fk_Pasajero_Terminal_idx` (`Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Pasajero_Terminal`
    FOREIGN KEY (`Terminal_idTerminal`)
    REFERENCES `mydb`.`Terminal` (`idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autobus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autobus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autobus` (
  `idAutobus` INT NOT NULL,
  `Empresa` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Fabricante` VARCHAR(45) NOT NULL,
  `Capacidad` INT NOT NULL,
  `Vigencia Seguro` DATE NOT NULL,
  `Disponibilidad` VARCHAR(2) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Terminal_idTerminal` INT NOT NULL,
  PRIMARY KEY (`idAutobus`, `Terminal_idTerminal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ruta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ruta` (
  `Terminal_idTerminal` INT NOT NULL,
  `Autobus_idAutobus` INT NOT NULL,
  `Autobus_Terminal_idTerminal` INT NOT NULL,
  `Locacion Inicial` VARCHAR(45) NULL,
  `Destino` VARCHAR(45) NULL,
  `Estimado Llegada` VARCHAR(45) NULL,
  `Hora programada` VARCHAR(45) NULL,
  `Id Ruta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Terminal_idTerminal`, `Autobus_idAutobus`, `Autobus_Terminal_idTerminal`, `Id Ruta`),
  INDEX `fk_Terminal_has_Autobus_Autobus1_idx` (`Autobus_idAutobus` ASC, `Autobus_Terminal_idTerminal` ASC) VISIBLE,
  INDEX `fk_Terminal_has_Autobus_Terminal1_idx` (`Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Terminal_has_Autobus_Terminal1`
    FOREIGN KEY (`Terminal_idTerminal`)
    REFERENCES `mydb`.`Terminal` (`idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terminal_has_Autobus_Autobus1`
    FOREIGN KEY (`Autobus_idAutobus` , `Autobus_Terminal_idTerminal`)
    REFERENCES `mydb`.`Autobus` (`idAutobus` , `Terminal_idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL,
  `Fecha salida` DATE NULL,
  `Hora Salida` TIME NULL,
  `Precio Tiquete` FLOAT NULL,
  `Modo Pago` VARCHAR(45) NULL,
  `Numero Acompañantes` VARCHAR(45) NULL,
  `Terminal_idTerminal` INT NOT NULL,
  `Ruta_Terminal_idTerminal` INT NOT NULL,
  `Ruta_Autobus_idAutobus` INT NOT NULL,
  `Ruta_Autobus_Terminal_idTerminal` INT NOT NULL,
  PRIMARY KEY (`idReserva`, `Terminal_idTerminal`, `Ruta_Terminal_idTerminal`, `Ruta_Autobus_idAutobus`, `Ruta_Autobus_Terminal_idTerminal`),
  INDEX `fk_Reserva_Terminal1_idx` (`Terminal_idTerminal` ASC) VISIBLE,
  INDEX `fk_Reserva_Ruta1_idx` (`Ruta_Terminal_idTerminal` ASC, `Ruta_Autobus_idAutobus` ASC, `Ruta_Autobus_Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Terminal1`
    FOREIGN KEY (`Terminal_idTerminal`)
    REFERENCES `mydb`.`Terminal` (`idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Ruta1`
    FOREIGN KEY (`Ruta_Terminal_idTerminal` , `Ruta_Autobus_idAutobus` , `Ruta_Autobus_Terminal_idTerminal`)
    REFERENCES `mydb`.`Ruta` (`Terminal_idTerminal` , `Autobus_idAutobus` , `Autobus_Terminal_idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipaje` (
  `idEquipaje` INT NOT NULL,
  `Dueño` VARCHAR(45) NULL,
  `Pasajero_idPasajero` INT NOT NULL,
  `Pasajero_Terminal_idTerminal` INT NOT NULL,
  `Peso` FLOAT NULL,
  `Sobre dimensionado` VARCHAR(45) NULL,
  `Valor extra` FLOAT NULL,
  PRIMARY KEY (`idEquipaje`),
  INDEX `fk_Equipaje_Pasajero1_idx` (`Pasajero_idPasajero` ASC, `Pasajero_Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Equipaje_Pasajero1`
    FOREIGN KEY (`Pasajero_idPasajero` , `Pasajero_Terminal_idTerminal`)
    REFERENCES `mydb`.`Pasajero` (`idPasajero` , `Terminal_idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idtable1` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Cedula` INT NOT NULL,
  `Disponibilidad` VARCHAR(2) NOT NULL,
  `Terminal_idTerminal` INT NOT NULL,
  PRIMARY KEY (`idtable1`, `Terminal_idTerminal`),
  INDEX `fk_Empleado_Terminal1_idx` (`Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Terminal1`
    FOREIGN KEY (`Terminal_idTerminal`)
    REFERENCES `mydb`.`Terminal` (`idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `Empleado_idtable1` INT NOT NULL,
  `Empleado_Terminal_idTerminal` INT NOT NULL,
  `Pasajero_idPasajero` INT NOT NULL,
  `Pasajero_Terminal_idTerminal` INT NOT NULL,
  `Tipo de servicio` VARCHAR(45) NULL,
  `Numero de servicio` INT NOT NULL,
  PRIMARY KEY (`Empleado_idtable1`, `Empleado_Terminal_idTerminal`, `Pasajero_idPasajero`, `Pasajero_Terminal_idTerminal`, `Numero de servicio`),
  INDEX `fk_Empleado_has_Pasajero_Pasajero1_idx` (`Pasajero_idPasajero` ASC, `Pasajero_Terminal_idTerminal` ASC) VISIBLE,
  INDEX `fk_Empleado_has_Pasajero_Empleado1_idx` (`Empleado_idtable1` ASC, `Empleado_Terminal_idTerminal` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_has_Pasajero_Empleado1`
    FOREIGN KEY (`Empleado_idtable1` , `Empleado_Terminal_idTerminal`)
    REFERENCES `mydb`.`Empleado` (`idtable1` , `Terminal_idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_has_Pasajero_Pasajero1`
    FOREIGN KEY (`Pasajero_idPasajero` , `Pasajero_Terminal_idTerminal`)
    REFERENCES `mydb`.`Pasajero` (`idPasajero` , `Terminal_idTerminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
