-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 19:29:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siap61db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siap61db` ;

-- -----------------------------------------------------
-- Schema siap61db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siap61db` DEFAULT CHARACTER SET utf8 ;
USE `siap61db` ;

-- -----------------------------------------------------
-- Table `siap61db`.`Salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Salon` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Salon` (
  `idSalon` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siap61db`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siap61db`.`Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Programa` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Programa` (
  `idPrograma` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrograma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siap61db`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Asignatura` (
  `idAsignatura` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `Programa_idPrograma` INT NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`, `Programa_idPrograma`, `Profesor_idProfesor`),
  INDEX `fk_Asignatura_Programa_idx` (`Programa_idPrograma` ASC) VISIBLE,
  INDEX `fk_Asignatura_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_Programa`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `siap61db`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `siap61db`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siap61db`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siap61db`.`Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Inscripcion` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Inscripcion` (
  `Asignatura_idAsignatura` INT NOT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  `fecha` DATE NULL,
  `nota` DECIMAL NULL,
  PRIMARY KEY (`Asignatura_idAsignatura`, `Estudiante_idEstudiante`),
  INDEX `fk_Asignatura_has_Estudiante_Estudiante1_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  INDEX `fk_Asignatura_has_Estudiante_Asignatura1_idx` (`Asignatura_idAsignatura` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_has_Estudiante_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `siap61db`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_has_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `siap61db`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siap61db`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siap61db`.`Horario` ;

CREATE TABLE IF NOT EXISTS `siap61db`.`Horario` (
  `Salon_idSalon` INT NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `dias` VARCHAR(45) NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`Salon_idSalon`, `Asignatura_idAsignatura`),
  INDEX `fk_Salon_has_Asignatura_Asignatura1_idx` (`Asignatura_idAsignatura` ASC) VISIBLE,
  INDEX `fk_Salon_has_Asignatura_Salon1_idx` (`Salon_idSalon` ASC) VISIBLE,
  CONSTRAINT `fk_Salon_has_Asignatura_Salon1`
    FOREIGN KEY (`Salon_idSalon`)
    REFERENCES `siap61db`.`Salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salon_has_Asignatura_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `siap61db`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
