-- MySQL Script generated by MySQL Workbench
-- Sat Aug 21 02:11:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siaAcademicodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siaAcademicodb` ;

-- -----------------------------------------------------
-- Schema siaAcademicodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siaAcademicodb` DEFAULT CHARACTER SET utf8 ;
USE `siaAcademicodb` ;

-- -----------------------------------------------------
-- Table `siaAcademicodb`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siaAcademicodb`.`Salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`Salon` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`Salon` (
  `idSalon` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siaAcademicodb`.`Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`Programa` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`Programa` (
  `idPrograma` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrograma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siaAcademicodb`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siaAcademicodb`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`Asignatura` (
  `idAsignatura` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Programa_idPrograma` INT NOT NULL,
  `Profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`, `Programa_idPrograma`, `Profesor_idProfesor`),
  INDEX `fk_Asignatura_Programa_idx` (`Programa_idPrograma` ASC) VISIBLE,
  INDEX `fk_Asignatura_Profesor1_idx` (`Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_Programa`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `siaAcademicodb`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_Profesor1`
    FOREIGN KEY (`Profesor_idProfesor`)
    REFERENCES `siaAcademicodb`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siaAcademicodb`.`Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`Inscripcion` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`Inscripcion` (
  `Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_Programa_idPrograma` INT NOT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  `fecha` DATE NULL,
  `nota` DECIMAL NULL,
  PRIMARY KEY (`Asignatura_idAsignatura`, `Asignatura_Programa_idPrograma`, `Estudiante_idEstudiante`),
  INDEX `fk_Asignatura_has_Estudiante_Estudiante1_idx` (`Estudiante_idEstudiante` ASC) VISIBLE,
  INDEX `fk_Asignatura_has_Estudiante_Asignatura1_idx` (`Asignatura_idAsignatura` ASC, `Asignatura_Programa_idPrograma` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_has_Estudiante_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura` , `Asignatura_Programa_idPrograma`)
    REFERENCES `siaAcademicodb`.`Asignatura` (`idAsignatura` , `Programa_idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_has_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `siaAcademicodb`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siaAcademicodb`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siaAcademicodb`.`horario` ;

CREATE TABLE IF NOT EXISTS `siaAcademicodb`.`horario` (
  `Asignatura_idAsignatura` INT NOT NULL,
  `Asignatura_Programa_idPrograma` INT NOT NULL,
  `Asignatura_Profesor_idProfesor` INT NOT NULL,
  `Salon_idSalon` INT NOT NULL,
  `dia` VARCHAR(45) NOT NULL,
  `hora` FLOAT NOT NULL,
  PRIMARY KEY (`Salon_idSalon`),
  INDEX `fk_Asignatura_has_Salon_Salon1_idx` (`Salon_idSalon` ASC) VISIBLE,
  INDEX `fk_Asignatura_has_Salon_Asignatura1_idx` (`Asignatura_idAsignatura` ASC, `Asignatura_Programa_idPrograma` ASC, `Asignatura_Profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_has_Salon_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura` , `Asignatura_Programa_idPrograma` , `Asignatura_Profesor_idProfesor`)
    REFERENCES `siaAcademicodb`.`Asignatura` (`idAsignatura` , `Programa_idPrograma` , `Profesor_idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignatura_has_Salon_Salon1`
    FOREIGN KEY (`Salon_idSalon`)
    REFERENCES `siaAcademicodb`.`Salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
