# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bxnlmAdVcBoo74lb6iVtTSV_qgo32hST
"""

#diccionarios

diccionarionuevo = {"llave " : "vlaor"} 

diccionarioNuevo = {"Nombre " : "enyupendi",
                    "Telefono ": 1234      , 
                    "Cedula":  "10232544"  }

sujeto_1 = {"Nombre " : "guadaña"   ,
            "Telefono ": 78632      , 
            "Cedula":  "10232544"  }
sujeto_2 = {"Nombre " : "cabito"   ,
            "Telefono ": 754544     , 
            "Cedula":  "23254104"  }              

listaDeDiccionarios = [sujeto_1,sujeto_2]       

diccionarioDeDiciconarios = {"misAmigos": [sujeto_1,sujeto_2]   ,
                             "otrasGentes" : [sujeto_2,sujeto_1]}

for i in diccionarioDeDiciconarios["misAmigos"]:
  print(i)
  print(i['Telefono '])


for keys, valor in diccionarioDeDiciconarios.items():
  print(keys)

  if keys == "misAmigos":
    print("estos son mis panas:", valor)

#____________________________________________________________________________________________________


diccionarionuevo = {"llave " : "vlaor"} 

diccionarioNuevo = {"Nombre " : "enyupendi",
                    "Telefono ": 1234      , 
                    "Cedula":  "10232544"  }

sujeto_1 = {"Nombre " : "guadaña"   ,
            "Telefono ": 78632      , 
            "Cedula":  "10232544"  }
sujeto_2 = {"Nombre " : "cabito"   ,
            "Telefono ": 754544     , 
            "Cedula":  "23254104"  }              

listaDeDiccionarios = [sujeto_1,sujeto_2]       

diccionarioDeDiciconarios = {"misAmigos": [sujeto_1,sujeto_2]   ,
                             "otrasGentes" : [sujeto_2,sujeto_1]}


for keys, valor in diccionarioDeDiciconarios.items():
  print(keys)

  if keys == "misAmigos":
    for i in keys:
      print(i)

# lista de tuplas en diccionario
a = [(1,4),(2,4),(3,4),(4,15),(5,15),(6,23),(7,23),(8,23),(9,15),(10,23),(11,15),(12,15)]
b = {}
print(a,b)
for i, j in a:

  b.setdefault(j, []).append(i)

print(a,b)