# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bxnlmAdVcBoo74lb6iVtTSV_qgo32hST
"""

def crear_lista(cadenaDeTexto):
  cadenaDeTexto = cadenaDeTexto + " " 
  listaRegalos = []
  substring = []

  for i in range(len(cadenaDeTexto)):
    if cadenaDeTexto[i] != " ":
      substring.append(cadenaDeTexto[i])
    elif cadenaDeTexto[i] == " ":
      listaRegalos.append(substring)
      substring = []
  
  listaDeRegalos = []
 
  for i in listaRegalos:
    element = ''.join(i)
    listaDeRegalos.append(element)
    element = ""

  #for i in listaRegalos:
  #  listaDeRegalos = listaDeRegalos + i

  return listaDeRegalos


def compararElementos(disponibles,deseados):
  regalos = crear_lista(deseados)   # lo convierto en una lista para comparar


  for k,v in  disponibles.items():
    if k in regalos :
      print(k)
      print("hay match",k,v)

    




productos = {"Radio": 48412, "Balon": 84619, "Pantalones": 91918}
listaFamilia = "Pony Bicicleta Oso Pantalones"

compararElementos(productos,listaFamilia)

#print(a) ; print(b)

#entradas
#{"Radio": 48412, "Balon": 84619, "Pantalones": 91918}
#Pony Bicicleta Oso Pantalones

#{"Movil": 16538, "Oso": 92573, "Zapatos": 51566, "Pony": 80126}
# Movil Camisas Balon

# {"Radio": 96563, "Balon": 20094, "Bicicleta": 97471}
#  Camisas Pantalones Bicicleta Radio Zapatos 


#outputs
#91918
#Pantalones

#16538
#Movil

#194034
#Bicicleta Radio

#_______________________________________________________________________________
def crear_lista(cadenaDeTexto):
  cadenaDeTexto = cadenaDeTexto + " " 
  listaRegalos = []
  substring = []

  for i in range(len(cadenaDeTexto)):
    if cadenaDeTexto[i] != " ":
      substring.append(cadenaDeTexto[i])
    elif cadenaDeTexto[i] == " ":
      listaRegalos.append(substring)
      substring = []
  
  listaDeRegalos = []
 
  for i in listaRegalos:
    element = ''.join(i)
    listaDeRegalos.append(element)
    element = ""

  #for i in listaRegalos:
  #  listaDeRegalos = listaDeRegalos + i

  return listaDeRegalos


def compararElementos(disponibles,deseados):
  regalos = crear_lista(deseados)   # lo convierto en una lista para comparar
  intercepcion = []

  total = 0
  for k,v in  disponibles.items():
    if k in regalos :
      intercepcion.append(k)
      total = total + v   # se suma el total a pagar 
  print(intercepcion,total)   
      

    




productos = {"Radio": 48412, "Balon": 84619, "Pantalones": 91918}
listaFamilia = "Pony Bicicleta Oso Pantalones"

compararElementos(productos,listaFamilia)

#print(a) ; print(b)

#entradas
#{"Radio": 48412, "Balon": 84619, "Pantalones": 91918}
#Pony Bicicleta Oso Pantalones

#{"Movil": 16538, "Oso": 92573, "Zapatos": 51566, "Pony": 80126}
# Movil Camisas Balon

# {"Radio": 96563, "Balon": 20094, "Bicicleta": 97471}
#  Camisas Pantalones Bicicleta Radio Zapatos 


#outputs
#91918
#Pantalones

#16538
#Movil

#194034
#Bicicleta Radio

#_______________________________________________________________________________
def crear_lista(cadenaDeTexto):
  cadenaDeTexto = cadenaDeTexto + " " 
  listaRegalos = []
  substring = []

  for i in range(len(cadenaDeTexto)):
    if cadenaDeTexto[i] != " ":
      substring.append(cadenaDeTexto[i])
    elif cadenaDeTexto[i] == " ":
      listaRegalos.append(substring)
      substring = []
  
  listaDeRegalos = []
 
  for i in listaRegalos:
    element = ''.join(i)
    listaDeRegalos.append(element)
    element = ""

  #for i in listaRegalos:
  #  listaDeRegalos = listaDeRegalos + i

  return listaDeRegalos


def compararElementos(disponibles,deseados):
  regalos = crear_lista(deseados)   # lo convierto en una lista para comparar
  intercepcion = ""

  total = 0
  for k,v in  disponibles.items():
    if k in regalos :
      intercepcion = intercepcion + " " + k
      total = total + v   # se suma el total a pagar
  intercepcion = intercepcion.lstrip()
  return(total,intercepcion)   
      

    




productos = {"Radio": 96563, "Balon": 20094, "Bicicleta": 97471}
listaFamilia = "Camisas Pantalones Bicicleta Radio Zapatos" 

a,b = compararElementos(productos,listaFamilia)

print(a) ; print(b)

#entradas
#{"Radio": 48412, "Balon": 84619, "Pantalones": 91918}
#Pony Bicicleta Oso Pantalones

#{"Movil": 16538, "Oso": 92573, "Zapatos": 51566, "Pony": 80126}
# Movil Camisas Balon

# {"Radio": 96563, "Balon": 20094, "Bicicleta": 97471}
#  Camisas Pantalones Bicicleta Radio Zapatos 


#outputs
#91918
#Pantalones

#16538
#Movil

#194034
#Bicicleta Radio