# Generated by Django 3.2.8 on 2021-10-08 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('idViajero', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_viajero', models.IntegerField()),
                ('telefono_viajero', models.IntegerField(default=0)),
                ('fechaDeNacimiento_viajero', models.DateTimeField()),
                ('isVip_viajero', models.BooleanField(default=False)),
                ('direccion_viajero', models.CharField(max_length=30, verbose_name='Direccion')),
                ('rh_viajero', models.CharField(max_length=30, verbose_name='RH')),
                ('eps_viajero', models.CharField(max_length=30, verbose_name='EPS')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
