# Generated by Django 3.2.8 on 2021-10-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaseAbordaje',
            fields=[
                ('idPaseAbordaje', models.AutoField(primary_key=True, serialize=False)),
                ('numeroVuelo_abordaje', models.IntegerField(null=True)),
                ('gate_abordaje', models.IntegerField(null=True)),
                ('asiento_abordaje', models.IntegerField(null=True)),
                ('origen_abordaje', models.CharField(max_length=30, null=True)),
                ('destino_abordaje', models.CharField(max_length=30, null=True)),
                ('numeroConfirmacion_abordaje', models.IntegerField(null=True)),
                ('aerolinea_abordaje', models.CharField(max_length=30, null=True)),
                ('grupo_abordaje', models.IntegerField(null=True)),
                ('fechaAbordaje_viajero', models.DateTimeField(null=True)),
                ('viajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.viajero')),
            ],
        ),
    ]
