# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sb_SPin_Wcbf-VpmuOqTQM6EKMS2WohI
"""

import json
import requests
from pprint import pprint

response = requests.get("https://jsonplaceholder.typicode.com/todos")
pendientes=json.loads(response.text)
#pprint(pendientes[:2])  # estructura [{'completed': False, 'id': 1, 'title': 'delectus aut autem', 'userId': 1}]

#pprint(pendientes)

pendientesPorUsuario = {}  # {'3': 1} asi seguarda id : tarea completada



# contar cantidad de elementos completados
for element in pendientes:
  if element["completed"]:  # se completo solo las que temrinan labor
    # print(element) los que acabaron su labor
    if element["userId"] in pendientesPorUsuario:   # ya tuve en cuenta el usuario?
      pendientesPorUsuario[ element["userId"] ]+=1
    
    else: # le anado un 1
      pendientesPorUsuario[  element["userId"] ] = 1

print(pendientesPorUsuario)

#contar la cantidad de elementos completados

import json
import requests
from pprint import pprint

response = requests.get("https://jsonplaceholder.typicode.com/todos")
pendientes=json.loads(response.text)
#pprint(pendientes[:2])  # estructura [{'completed': False, 'id': 1, 'title': 'delectus aut autem', 'userId': 1}]



pendientesPorUsuario = {}  # {'3': 1} asi seguarda id : tarea completada



# contar cantidad de elementos completados
for element in pendientes:
  if element["completed"]:  # se completo solo las que temrinan labor
    # print(element) los que acabaron su labor
    if element["userId"] in pendientesPorUsuario:   # ya tuve en cuenta el usuario?
      pendientesPorUsuario[ element["userId"] ]+=1
    
    else: # le anado un 1
      pendientesPorUsuario[  element["userId"] ] = 1

itemsOrdenados = sorted(pendientesPorUsuario.items() , key = lambda x: x[1] , reverse= True)  # ordenar los elemntos

print(itemsOrdenados) # [(5, 12), (10, 12), (1, 11), (8, 11), (7, 9), (2, 8), (9, 8), (3, 7), (4, 6), (6, 6)] 

maximasTareasCompletadas = itemsOrdenados[0][1]
usuario = []

for user, numTareaCom in itemsOrdenados:
  if numTareaCom == maximasTareasCompletadas:
    usuario .append(str(usuario))
  else:
    break
usuariosConMaximo = "y".join(usuario ) # concatena 2 variable con un elemnto intermedio
print("Los usuarios = ",usuariosConMaximo, "han completado ", maximasTareasCompletadas, " tareas" )